version: '2'

services:

  bibbox-mantis:
    # debug
#    build: ./images/mantis # for debug
    image: bibbox/mantis
    container_name:  bibbox-mantis
    links:
      - bibbox-mantis-db:mantis-db
    ports:
      - "8065:80"
    depends_on:
      - bibbox-mantis-db
      - bibbox-mantis-data
    volumes_from: 
      - bibbox-mantis-data

  bibbox-mantis-db:
    image: mariadb
    container_name: bibbox-mantis-db
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=mantis4bibbox
      - MYSQL_DATABASE=bugtracker
      - MYSQL_USER=mantis
      - MYSQL_PASSWORD=mantis4bibbox
    volumes_from: 
      - bibbox-mantis-data
    depends_on:
      - bibbox-mantis-data

  bibbox-mantis-data:
    image: busybox
    container_name: bibbox-mantis-data
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql
